server {
    listen 80;
    server_name hashtopolis.*;
    return 308 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name hashtopolis.*;

    ssl_certificate     /path/to/nginx.crt;
    ssl_certificate_key /path/to/nginx.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 2G;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location ~ (.*\.php) {
        proxy_pass http://hashtopolis-backend/$request_uri;
    }

    location /api {
        proxy_pass http://hashtopolis-backend/api;
    }

    location /static {
        proxy_pass http://hashtopolis-backend/static;
    }

    location / {
        proxy_pass http://hashtopolis-frontend;
    }

    location /legacy {
        proxy_pass http://hashtopolis-backend/index.php;
    }
}
